config/routes.rb
Snote::Application.routes.draw do
  devise_for :users

  root :to => "notes#index"
  resources :notes
  match 'notes/example' => "notes#example"
  match 'notes/search' => "notes#search"
  match 'notes/share/:id' => "notes#share", :as => 'note_share'
  match "public/notes/:user/:note_id" => "notes#show", :as => 'post_note'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable_on :tags
  acts_as_textiled :text
  validates_presence_of :text

  before_save :sanitize

  def self.find_my_notes(current_user_id)
    all(:conditions => "notes.user_id = #{current_user_id}",:order=>"id DESC")
  end

  def self.find_all_tags(notes)
    tags = []
    notes.each do |note|
      note.tags.each{|tag| tags << tag.name if !tags.include?(tag.name)}
    end
    tags
  end

  def self.with_tag(tag, current_user_id)
    all(:conditions => ["tags.name LIKE ? AND notes.user_id = ?","%#{eval("tag")}%", current_user_id],
        :joins => "INNER JOIN taggings ON taggings.taggable_id = notes.id
          INNER JOIN tags ON taggings.tag_id = tags.id")
  end

  def self.find_public_note(user_id, note_id)
    Note.all(:conditions => {:private => false, :user_id => user_id, :id => note_id}).first
  end

  def sanitize
    text_string = self.text.downcase
    if text_string.include?('<script>') && text_string.include?('</script>')
      new_text = ''
      self.text.split(' ').each do |t|
        if t.include?('script')
          new_text << "\"#{t}\""
        else
          new_text << t
        end
      end
      self.text = new_text
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :notes, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :language

  validates_presence_of :username
  validates_uniqueness_of :username, :case_sensitive => false
  validates_format_of :username, :with => /^[A-Za-z\d_]+$/

  def self.languages
    {'pt-BR' => 'Portugues', 'en' => 'English'}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_language

  def can_access?
    current_user.id == @note.user_id
  end


  private
  def set_language
    if !current_user.nil? && defined?(current_user.language)
      I18n.locale = current_user.language || I18n.default_locale
    end
  end
end

app/controllers/notes_controller.rb
# coding: utf-8
class NotesController < ApplicationController

  before_filter :authenticate_user!, :except => [:show]
  before_filter :update_username
  layout :choose_layout

  def index
    @search = params[:search]
    if @search.blank?
      @notes = Note.find_my_notes(current_user.id)
    else
      @notes = Note.with_tag(@search, current_user.id)
    end
    @username = current_user.username.downcase
    @tags = Note.find_all_tags(@notes)
    respond_to do |format|
      format.js if request.xhr?
      format.html
    end
  end

  def show
    user_username = params[:user]
    note_id = params[:note_id]
    @user = User.find(:first, :conditions => [ "lower(username) = ?", user_username.downcase ])
    if !@user.blank?
      @note = Note.find_public_note(@user.id, note_id)
    end
  end

  def new
    @note = Note.new
    respond_to do |format|
      format.html
    end
  end

  def edit
    @note = Note.find(params[:id])
    @note.textiled = false
    redirect_to notes_path unless can_access?
  end

  def share
    note = Note.find(params[:id])
    note.private = false
    note.save
    respond_to do |format|
      format.js
    end
  end

  def create
    @note = Note.new(params[:note])
    @note.textiled = false
    @note.tag_list = params[:tags]
    @note.user_id = current_user.id
    respond_to do |format|
      if @note.save
        format.html { redirect_to(notes_url, :notice => 'Anotação criada com sucesso!') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @note = Note.find(params[:id])
    @note.textiled = false
    @note.tag_list = params[:tags]
    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(notes_url, :notice => 'Anotação atualizada com sucesso!') }
        format.js
      else
        format.html { render :action => "edit" }
        format.js
      end
    end
  end

  def destroy
    @note = Note.find(params[:id])
    redirect_to notes_path unless can_access?
    @note.destroy
    respond_to do |format|
      format.html { redirect_to(notes_url) }
    end
  end

  def example
  end

private

  def choose_layout
    if [ 'show'].include? action_name
      'public'
    else
      'application'
    end
  end

  def update_username
    if !current_user.nil?
     redirect_to edit_user_registration_path if current_user.username.blank?
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def google_analytics
    render :partial => 'shared/analytics' if Rails.env == 'production'
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.haml
!!!
%html(lang='pt-BR')
  %head
    %meta(charset='utf-8')
    %title Snote - notes made easy
  = stylesheet_link_tag :all
  = javascript_include_tag 'jquery/jquery-1.5.1.min.js'
  = javascript_include_tag 'jquery/jquery-ui-1.8.11.custom.min.js'
  = javascript_include_tag 'jquery-rails.js'
  = javascript_include_tag 'jquery.colorbox-min.js'
  = csrf_meta_tag

  %body
    #snote
      #logo
        = link_to (image_tag "/images/snote_title.png", :alt => "Snote",
          :title =>"Snote"), root_path
      - if current_user
        #links_menu
          - if current_user.email != 'demo@snote.com'
            = link_to I18n.t('user.edit_link'), edit_user_registration_path
            |
          = link_to I18n.t('logout'), destroy_user_session_path

      = yield
    = google_analytics
  :javascript
    $('form').submit(function(){
      // On submit disable its submit button
      $('input[type=submit]', this).attr('disabled', 'disabled');
      $('input[type=submit]', this).attr('value', "#{t('please_wait')}");
    });

app/views/layouts/public.html.haml
!!!
%html(lang='pt-BR')
  %head
    %meta(charset='utf-8')
    %title Snote - notes made easy
  = stylesheet_link_tag :all
  <link href='http://fonts.googleapis.com/css?family=Just+Another+Hand' rel='stylesheet' type='text/css'>
  = csrf_meta_tag
  %body
    #snote
      #logo
        = link_to (image_tag "/images/snote_title.png", :alt => "Snote",
          :title =>"Snote"), root_path
      = yield
    = google_analytics

app/views/notes/_form.html.haml
.Left
  = form_for(@note) do |f|
    - if @note.errors.any?
      .error_explanation
      %h2
        = pluralize(@note.errors.count, I18n.t('error'))
      %ul
        - @note.errors.full_messages.each do |msg|
          %li
            = msg

    .field
      = f.label :text, t('note.textk')
      %br
      = f.text_area :text
    .field
      = label_tag :tags
      %br
      = text_field_tag :tags, @note.tag_list.join(', ')
    .actions
      = f.submit :disable_with => I18n.t('please_wait')
    = link_to I18n.t('back'), notes_path
.Right
  #help_text
  %h2= t('format.title')
  %p= t('format.desc', :textile_link => link_to('Textile', "http://redcloth.org/hobix.com/textile/", :target => "_blank")).html_safe
  %p= t('format.examples')
  .textileexamples
    %p
      = "*"+t('format.bold')+"*"
      → 
      %strong= t('format.bold')
    %p
      = "_"+t('format.italic')+"_"
      → 
      %em= t('format.italic')
    %p
      "link":http://google.com →
      = link_to "link","http://google.com", :target => "_blank"
    %p
      pre. →  
      = t('format.pre')
    %p
      * → 
      = t('format.ul')
    %p
      ** → 
      = t('format.2ndlevel')
    %p
      \# → 
      = t('format.ol')
    %p
      \## → 
      = t('format.2ndlevel')
    %p= t('format.see', :link => link_to(t('format.example'),notes_example_path, :target=> "_blank")).html_safe

app/views/notes/_list.html.haml
- notes.each do |note|
  .note
    .buttons
      = button_to I18n.t('note.delete'), {:action => 'destroy', :id => note.id}, :method => :delete, :class => 'links_button'
      = button_to I18n.t('note.edit'), {:action => 'edit', :id => note.id}, :method => :get, :class => 'links_button'
      - if note.private
        = link_to I18n.t('note.share'), {:action => 'share', :id => note.id}, {:remote => true, :class => 'links_button share', :id => "share_#{note.id}"}
      - else
        = link_to I18n.t('note.share'), nil, {:class => 'links_button share', :id => "share_#{note.id}"}

    =raw note.text
    .tags
      - note.tags.each do |tag|
        %li
          =  tag.name
  %div{:style => 'display:none'}
    %div{:id => "inline_note_#{note.id}"}
      <script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
      %div
        .share_title
          Compartilhe a sua anotação:
        .share_options
          Link público:
          %a{:href => "#{post_note_url(:user => @username, :note_id => note.id)}", :class => "public_link", :target => "_blank"}
            = post_note_url(:user => @username, :note_id => note.id)
          .tweet_button
            %a{:href => "http://twitter.com/share", :class => "twitter-share-button",
               "data-url" => "#{post_note_url(:user => @username, :note_id => note.id)}",
               "data-via" => "snote_app",
               "data-text" => "#{t('my_new_note')}",
               "data-count" => "none"}
              Tweet
  :javascript
    $(document).ready(function() {
      $("#share_#{note.id}").colorbox({width:"50%", inline:true, href:"#inline_note_#{note.id}"});
    });

app/views/notes/edit.html.haml
#form
  %h1 
    = I18n.t('note.editing')
  = render 'form'

app/views/notes/example.html.haml
.Left{:style => "clear:left;width:47%;padding-right:10px;"}
  .example_title
    %h2 Versão Textile:
  %p h1. Exemplo de texto usando _Textile_
  %p O *Snote* nasceu da necessidade de seu criador, em manter as suas anotações.
  %p p. Ele é focado em gerenciar anotações, buscando ser:
  %p
    * Fácil
    %br
    ** Quando estamos criando uma anotação, queremos que ela seja criada de uma forma fácil, afinal se for muito difícil ou chato escrever a anotação, acabamos nem anotando nada.
    %br
    * Rápido
    %br
    ** Criar uma anotação deve ser uma tarefa rápida, pois caso contrário, acabamos não registrando uma anotação que pode ser importante no futuro.

  %p h2. Texto pré-formatado

  %p Com o Snote podemos por exemplo, adicionar textos pré-formatados de duas formas.

  %p pre. sudo apt-get install ruby

  %p No caso em que o texto pré-formatado tiver mais de uma linha, podemos usar:

  %p pre.. sudo apt-get install ruby rubygems
  %p sudo gem install rails

  %p p. Para encerrar um texto pré-formatado de várias linhas utilizando a tag *pre..*, precisamos iniciar um novo bloco de forma implícita, utilizando por exemplo o *p.*.

  %p Uma forma mais fléxivel de criar texto pré-formatado, é utilizar a própria tag do _html_ *pre*:

  %p
    =h "<pre>sudo apt-get install ruby rubygems"
    %br
    =h "sudo gem install rails</pre>"

  %p Como acabamos de ver, também podemos utilizar todas as tags _html_ em nossas anotações. E com isso juntamos o melhor de dois mundos:

  %p
    \# A simplicidade da linguagem de marcação _Textile_;
    %br
    \# A flexibilidade e marcações avançadas do _html_.
  %p
    h2. Tabela
  %p
    table{border:1px solid black}.
    %br
      |\2=. Super-Heróis|
    %br
      |_. super-herói|_. Nome|
    %br
      |Homem-Aranha|Peter Park|
    %br
      |Homem de Ferro|Tony Stark|
    %br
      |Super-Homem|Clark Kent|
    %br
      |Batman|Bruce Wayne|
  %p
    h2. Alinhamento
  %p
    p<. Esquerda
  %p
    p>. Direita
  %p
    p=. Centro
  %p
    h2. Citações
  %p
    bq. Esta é uma citação
  %p
    Outra forma de citar é:
  %p
    bq.. Esta é uma outra citação
  %p
    Com dois parágrafos.
  %p
    h2. Notas de página
  %p
    O projeto do Snote é _opensource_ e seu código está disponível no Github.[1]
  %p
    fn1. "Github":http://github.com/Vizir/snote
  %p
    h2. Saiba mais
  %p
    Saiba mais marcações em: "http://redcloth.org/textile":http://redcloth.org/textile

.Right{:style => "width:51%;border-left:1px solid;padding-left:10px;"}
  .example_title
    %h2 Versão renderizada:
  :textile
    h1. Exemplo de texto usando _Textile_

    O *Snote* nasceu da necessidade de seu criador, em manter as suas anotações.

    p. Ele é focado em gerenciar anotações, buscando ser:
    * Fácil
    ** Quando estamos criando uma anotação, queremos que ela seja criada de uma forma fácil, afinal se for muito difícil ou chato escrever a anotação, acabamos nem anotando nada.
    * Rápido
    ** Criar uma anotação deve ser uma tarefa rápida, pois caso contrário, acabamos não registrando uma anotação que pode ser importante no futuro.

    h2. Texto pré-formatado

    Com o Snote podemos por exemplo, adicionar textos pré-formatados de duas formas.

    pre. sudo apt-get install ruby

    No caso em que o texto pré-formatado tiver mais de uma linha, podemos usar:

    pre.. sudo apt-get install ruby rubygems
    sudo gem install rails

    p. Para encerrar um texto pré-formatado de várias linhas utilizando a tag *pre..*, precisamos iniciar um novo bloco de forma implícita, utilizando por exemplo o *p.*.

    Uma forma mais fléxivel de criar texto pré-formatado, é utilizar a própria tag do _html_ *pre*:

    <pre>sudo apt-get install ruby rubygems
    sudo apt-get install rails</pre>

    Como acabamos de ver, também podemos utilizar todas as tags _html_ em nossas anotações. E com isso juntamos o melhor de dois mundos:
    # A simplicidade da linguagem de marcação _Textile_;
    # A flexibilidade e marcações avançadas do _html_.

    h2. Tabela

    table{border:1px solid black}.
    |\2=. Super-Heróis|
    |_. super-herói|_. Nome|
    |Homem-Aranha|Peter Park|
    |Homem de Ferro|Tony Stark|
    |Super-Homem|Clark Kent|
    |Batman|Bruce Wayne|

    h2. Alinhamento

    p<. Esquerda

    p>. Direita

    p=. Centro

    h2. Citações

    bq. Esta é uma citação

    Outra forma de citar é:

    bq.. Esta é uma outra citação

    Com dois parágrafos.

    h2. Notas de página

    O projeto do Snote é _opensource_ e seu código está disponível no Github.[1]

    fn1. "Github":http://github.com/Vizir/snote

    h2. Saiba mais

    Saiba mais marcações em: "http://redcloth.org/textile":http://redcloth.org/textile

app/views/notes/index.html.haml
.new
  = link_to I18n.t('note.new'), new_note_path, :class => 'links_button'
- if @notes.size > 0
  #search_bar
    - form_tag do
      = text_field_tag :search, '', :size => 20
      = button_to(t('search'), url_for(:action => :search), :remote => true, :disable_with => t('please_wait_searching'), :id => 'search_submit')
#notes
  = render :partial => "list", :locals => {:notes => @notes}
  - if @notes.size == 0 && @search.nil?
    <link href='http://fonts.googleapis.com/css?family=Cabin+Sketch:bold' rel='stylesheet' type='text/css'>
    #zero_notes
      = t('note.zero_notes').html_safe
  - elsif @notes.size == 0 && !@search.nil?
    <link href='http://fonts.googleapis.com/css?family=Cabin+Sketch:bold' rel='stylesheet' type='text/css'>
    #zero_notes
      = t('note.not_found').html_safe
:javascript
  $(document).ready(function(){
    var data = #{array_or_string_for_javascript(@tags)};
    $( "#search" ).autocomplete({
      source: data
    });
  });

app/views/notes/new.html.haml
#form
  %h1 
    = I18n.t('note.creating')
  = render 'form'

app/views/notes/show.html.haml
- if @note.nil?
  <link href='http://fonts.googleapis.com/css?family=Cabin+Sketch:bold' rel='stylesheet' type='text/css'>
  #zero_notes
    = t('note.not_found').html_safe
- else
  .note
    =raw @note.text
    .tags
      - @note.tags.each do |tag|
        %li
          =  tag.name
    .powered_by
      = "<span>#{I18n.t('note.powered_by')}</span> #{@user.username}".html_safe

app/views/shared/_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-5295321-6']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script');
    ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 
    'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; 
    s.parentNode.insertBefore(ga, s);
  })();